### ISSUE TITLE
Want to kindly ask to the post request

### ISSUE THREAD

**Issue by vst212** [ThePhaseless/Byparr#19]
the cloudflare sometime, we need to send post request and add header of x-acces-token and the data json, currently is it any method to achieve? I see this in previos version of FlareSolverr but was removed, may I kindly ask that is it still possible to achieve this?

Thank your ery much in advance.

**Comment by ThePhaseless** [comment]
Hi, currently I'm working on a remade version on Byparr, but currently, you can make a request with get to byparr and then use cookies and headers from response in post request directly to your website. Would this work you for now?

**Comment by vst212** [comment]
this is really a problem as if in the first connection to Byparr, it has "cookies": [
      {
        "domain": ".stake.bet",
        "httpOnly": true,
        "name": "_cfuvid",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "value": "8qOWrdqJPV1bdiJ2ZkWrxXUBX2ZLL1QZCDxeBBe4tcc-1732547971807-0.0.1.1-604800000"
      },
      {
        "domain": ".stake.bet",
        "expiry": 1732549771,
        "httpOnly": true,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "value": "9f1BJitS4hJSmHrlTv9woPXlJSNlbAaoez2dRY.Bd60-1732547971-1.0.1.1-O08_gngt0U3u2oBi5I.De0Akrr3lKApYfPhfz4LaY_7aUY70XQxTxTjn0zUEjqlcIC0uFxwuId5wR_sadvhhQw"
      }
    ],

which is not consist of cf_clerence and the cookie and domain added "x-access-token" as often with using the IP, useragent and cookie to creat post request, as header added  "x-access-token" , it get blocked: <html lang="en-US"><head><title>Just a moment...</title>

**Comment by ThePhaseless** [comment]
Unfortunately, seleniumbase does not support post requests as it is only capable of using browser as a request handler, which only supports GET requests. In your case, probably what's happening is that your browser/client that you are trying to send post request from is getting a challenge, but byparr does not. Please try this flow:
1. Make a request from your client
2. If challenge is present then send a request to byparr for cookies
3. Byparr should also get a request bcs you failed the 1st test from this ip (in your client)
4. You should get `cf_clerence` cookies in the response

I am going to mark this as not planned mainly because it is problem with seleniumbase itself rather than my implementation of it
